// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_kr5wgWgxo1HWUF6l5U0nRyWP5nXfQA',
    appId: '1:30607756645:web:4792fbbb297956fa43658c',
    messagingSenderId: '30607756645',
    projectId: 'billetterieevent-a023d',
    authDomain: 'billetterieevent-a023d.firebaseapp.com',
    storageBucket: 'billetterieevent-a023d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bYjB3SJ_i64hqXNzNLEHFsTzMgtx_yc',
    appId: '1:30607756645:android:458a72b3bf9a914243658c',
    messagingSenderId: '30607756645',
    projectId: 'billetterieevent-a023d',
    storageBucket: 'billetterieevent-a023d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjCg480bEswsUKKnnJ-QSrXdu6CJc4h3o',
    appId: '1:30607756645:ios:1e390ebc90f8122043658c',
    messagingSenderId: '30607756645',
    projectId: 'billetterieevent-a023d',
    storageBucket: 'billetterieevent-a023d.firebasestorage.app',
    iosClientId: '30607756645-91raca8l4nho1c2dec05cr074ej9ptrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.billetterieEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjCg480bEswsUKKnnJ-QSrXdu6CJc4h3o',
    appId: '1:30607756645:ios:1e390ebc90f8122043658c',
    messagingSenderId: '30607756645',
    projectId: 'billetterieevent-a023d',
    storageBucket: 'billetterieevent-a023d.firebasestorage.app',
    iosClientId: '30607756645-91raca8l4nho1c2dec05cr074ej9ptrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.billetterieEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_kr5wgWgxo1HWUF6l5U0nRyWP5nXfQA',
    appId: '1:30607756645:web:49e896b8d6d421e443658c',
    messagingSenderId: '30607756645',
    projectId: 'billetterieevent-a023d',
    authDomain: 'billetterieevent-a023d.firebaseapp.com',
    storageBucket: 'billetterieevent-a023d.firebasestorage.app',
  );
}
